name: Docs issue
description: Report a docs problem (missing steps, unclear wording, broken link)
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What is wrong
      placeholder: "What page, what section, what is unclear or broken?"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix
    validations:
      required: false
